### ISSUE TITLE
[Settings.watchKeys] not being fired

### ISSUE THREAD

**Issue by kikoseijo** [aMarCruz/react-native-cross-settings#2]
Hi there, 

Im trying to implement it on iOS but does not seem to work the watchkeys feature.
For some reason the subscription gets called but the callback does not get fired.

The problem does not have to do with your library as iOS its taken directly from react-native,

I was wondering if you had any issues? Or I'm missing something on the native part.

 I'm running *React-native 16.3.0* with *react-native init*.

Appreciate any tips, and, thanks in advance.

**Comment by aMarCruz** [comment]
@kikoseijo sorry, my work is targeting Android only and I know nothing about iOS ...I don't have a Mac.

Anyway, the internal JS code for RN Settings is not very efficient (because iOS backend?) but seems correct, maybe someone from the community can help on this.

**Comment by kikoseijo** [comment]
Thanks for response, much appreciated.
Mobx did the job for me this time!.
